const ProjectData = [
  {
    id: 1,
    title: "Quiz App",
    category: "React",
    github: "https://github.com/japhmayor/react-quiz-app",
    img: "./images/quiz.jpeg",
    website: "https://quizzical-einstein-4b55fb.netlify.app",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "Markdown Preview",
    category: "React",
    github: "https://github.com/Japhmayor/markdown-preview",
    img: "./images/markdown.jpeg",
    website: "https://silly-boyd-8a4648.netlify.app",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 3,
    title: "Color Generator",
    category: "React",
    github: "https://github.com/japhmayor/color-generator",
    img: "./images/color.jpeg",
    website: "https://silly-boyd-8a4648.netlify.app",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 4,
    title: "Expense tracking app",
    category: "Working on ...",
    github: "https://github.com",
    img: "./images/item-7.jpeg",
    website: "https://github.com",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 5,
    title: "Media streaming app",
    category: "Working on ...",
    github: "https://github.com",
    img: "./images/item-7.jpeg",
    website: "https://github.com",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 6,
    title: "VR game for web",
    category: "Working on ...",
    github: "#",
    img: "./images/item-7.jpeg",
    website: "#",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 7,
    title: "Dark Mode",
    category: "React",
    github: "https://github.com/japhmayor/react-darkmode",
    img: "./images/darkmode.jpeg",
    website: "https://admiring-pare-144644.netlify.app/",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 8,
    title: "Landing page",
    category: "UI",
    github: "https://github.com/japhmayor/meyo-landing",
    img: "./images/landing.png",
    website: "https://meyolanding.netlify.app/",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
];
export default ProjectData;
