const ProjectData = [
  {
    id: 1,
    title: "Quiz App",
    category: "React",
    github: "https://github.com/japhmayor/react-quiz-app",
    img: "./images/quiz.jpeg",
    website: "https://quizzical-einstein-4b55fb.netlify.app",
    desc: ` A quiz app i built to learn how to consume API's in React. `,
  },
  {
    id: 2,
    title: "Markdown Preview",
    category: "React",
    github: "https://github.com/Japhmayor/markdown-preview",
    img: "./images/markdown.jpeg",
    website: "https://silly-boyd-8a4648.netlify.app",
    desc: `I couldn't get myself to learn Markdown for my ReadMe's, so i decided to make a preview. `,
  },
  {
    id: 3,
    title: "Color Generator",
    category: "React",
    github: "https://github.com/japhmayor/color-generator",
    img: "./images/color.jpeg",
    website: "https://silly-boyd-8a4648.netlify.app",
    desc: ` This is a color generator built with react. I will discuss how i built this in a blogpost `,
  },
  {
    id: 4,
    title: "Expense tracking app",
    category: "Working on ...",
    github: "https://github.com",
    img: "./images/item-7.jpeg",
    website: "https://github.com",
    desc: ` This is what i thought off when i decided to build a fintech app. It's still in the works `,
  },
  {
    id: 5,
    title: "Media streaming app",
    category: "Working on ...",
    github: "https://github.com",
    img: "./images/item-7.jpeg",
    website: "https://github.com",
    desc: ` This is still in the works. My own Youtube `,
  },
  {
    id: 6,
    title: "VR game for web",
    category: "Working on ...",
    github: "#",
    img: "./images/item-7.jpeg",
    website: "#",
    desc: `I am still working on this using React 360 `,
  },
  {
    id: 7,
    title: "Dark Mode",
    category: "React",
    github: "https://github.com/japhmayor/react-darkmode",
    img: "./images/darkmode.jpeg",
    website: "https://admiring-pare-144644.netlify.app/",
    desc: ` Details will be in a blog post I will write soon `,
  },

  {
    id: 9,
    title: "Dictionary",
    category: "Vue",
    github: "https://github.com/japhmayor/meyo-dictionary",
    img: "./images/dict.png",
    website: "https://meyodictionary.netlify.app/",
    desc: ` I built this dictionary whilst learning how to consume API's in Vue  `,
  },
  {
    id: 10,
    title: "my Portfolio",
    category: "React",
    github: "https://github.com/japhmayor/meyo",
    img: "./images/mine.png",
    website: "https://uyo-meyo.netlify.app/",
    desc: `This website you are viewing built with React. I didn't hard code anything, Everything is flexible and pluggable. You can clone the repo add your projects to ProjectData.js and your work experience to Data.js and your portfolio is ready `,
  },
  {
    id: 11,
    title: "Note taking app",
    category: "Vue",
    github: "https://github.com/japhmayor/note-app",
    img: "./images/note.png",
    website: "https://notz.netlify.app/",
    desc: ` A notetaking app for taking notes. I built this to learn how to create a PWA in Vue. `,
  },
];
export default ProjectData;
